const names = "shubham sharma"; // isme data ko change nhi kar sakhte hai ,, constant hai yeh

let fatherName = "ujjwal sharma";// yeh same c++ ka int,float jaisa hai...

var motherName = "sheela devi"; // yeh humlog use nhi karenge bcoz isme block scope yeh functional scope naam ka koi chiz hi nhi hai ...

height = "5feet 11inch" // aise v likh sakhte hai ,, but yeh ek bad practise hai ....

console.table([names,fatherName,motherName,height]);