const clock = document.querySelector("#clock"); // yeha se maine clock id ko select kiya ...

setInterval(() => {                             // set interval maine isi liye use kiye ,, bcoz mujhe time seconds mai show karne the isi liye...
    let dates = new Date();                     // date object hai JS mai ,, jo current date and time de deta hai..
    clock.innerHTML = dates.toLocaleTimeString(); // yeha maine clock mai dates se jo v value aayi thi usko time mai convert kiya and store kar diya...
}, 1000);                                         // yeha kitne time interval mai load karna hai time vo show karte hai yeha harr ek second mai show karna hai isi liye 1000 daale ...