// Immediately Invoked Function Expressions (IIFE)
//global scope ke pollution se problem hoti hai kai baar toh usse bachne ke liye humlog iife use karte hai...
//yeh humare function ko turant execute kar deta hai ...

(function chai(){
    // named IIFE
    console.log(`DB CONNECTED`);
})();   // agar yeha ; nhi lagayenge toh neeche function jo likhenge vo execute nhi hoga ...

//() pehla parenthesis mai function declare hota hai...
//() second parenthesis mai function execution ...

( (name) => {
    console.log(`DB CONNECTED TWO ${name}`);
} )('hitesh')
